version = 1

[install]
nodejs_24.pkg-path = "nodejs_24"
nodejs_24.version = "^24.12.0"

claude-code.pkg-path = "claude-code"
claude-code.version = "2.1.14"

[hook]
on-activate = """
  npm install
"""
